FROM oven/bun:1.3.1-alpine AS build

WORKDIR /app

COPY package.json bun.lock ./

RUN bun install --frozen-lockfile

COPY tsconfig.json ./

COPY src ./src

RUN bun run build

FROM alpine:3.20

RUN apk add --no-cache libstdc++ libgcc

WORKDIR /app

COPY --from=build /app/dist/nabu-auth ./nabu-auth

EXPOSE 5555

USER 1000

ENTRYPOINT ["./nabu-auth"]

